server:
  port: 8088


spring:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect&useSSL=false
    password: 123456
  redis:
    host: 81.69.251.187
    port: 6379
    password: huanghao666
    database: 1

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl