server:
  port: 80


spring:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect&useSSL=false
    password: root
  redis:
    host: 81.69.251.187
    port: 6379
    password: huanghao666
    database: 0